pagarme/woocommerce

src/View/Checkouts.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-290
| **What?**         | Fixed copy raw qrcode
=> Fixed copy raw qrcode

src/Concrete/WoocommerceCoreSetup.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-302
| **What?**         | Fixed card brand names
=> :bug: fixed brand names

.plugin-data/README.md, composer.json, constants.php, package.json, readme.md, woo-pagarme-payments.php
This version bump includes:
- #64
=> Bump version 1.2.2

src/Controller/Gateways.php, src/View/Orders.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-399
| **What?**         | Fixes output of a option in module configuration and the capture charge button
| **Why?**          | To allow user to interact with the module correctly
| **How?**          | Doing the correct output handling and fixing a error in capture button display logic.
=> Fix some outputs in module identified after changes requested by wordpress.org

src/Concrete/WoocommerceCoreSetup.php, src/Model/Setting.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-435
| **What?**         | Fix installments by card brand
| **How?**          | Sanitizing the installment type field when save the configuration
=> 🐛 Fix installments by card brand

templates/checkout/main.php
| **What?**      | bugfix at installments load
| **How?**       | remove the jquery instance at main.php
=> :bug: bugfix at installments load

.plugin-data/README.md, assets/javascripts/front/main.js, composer.json, constants.php, package.json, woo-pagarme-payments.php
| **What?**      | Fix Sweetalert2 object instantiate 
| **How?**       | Adding try catch to verify how it does
=> :bug: Added try and catch to instantiate sweetalert2 in diferents versions

vendor/pagarme/ecommerce-module-core/src/Webhook/Services/WebhookReceiverService.php
| **What?**         | Blur sensitive data from log
| **Why?**          | Improve the security
| **How?**          | Adding a mask in fields with sensitive data
=> Added method to prepare data before log

vendor/pagarme/ecommerce-module-core/src/Kernel/Services/LogService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-56
| **What?**         | Blur sentitive data at logs files
| **Why?**          | Personal data can not be displayed 
| **How?**          | Adding a function for blur all the client data at log service
=> :art: changed pattern of blur sensitive data

src/Concrete/WoocommercePlatformOrderDecorator.php, src/Model/Order.php
improve need_processing and charge.paid webhook
=> :bug: improve need_processing and charge.paid webhook

src/Concrete/WoocommercePlatformOrderDecorator.php
Removing the order status comparison to the status it will change.
=> :bug: removing the order status comparison to the status it will change.

src/Concrete/WoocommercePlatformOrderDecorator.php, src/Controller/Checkout.php, src/Controller/Gateways.php, src/Model/Payment.php, templates/checkout/voucher-item.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php, vendor/pagarme/ecommerce-module-core/src/Payment/Factories/PaymentFactory.php
Implementation of the multi-buyer functionality for the voucher payment type
=> PAOPN-94: add multi-buyer on voucher payments

assets/javascripts/front/main.js, src/Core.php
fix pt_br translations on checkout errors
=> PAOPN-257: fix pt_br translations on checkout error

.circleci/config.yml, .github/workflows/pr.yml, sonar-project.properties
Convertendo o CI do CircleCI para o GA 
Não foi alterado a parte de CD
=> Convert CircleCI

src/Concrete/WoocommercePlatformOrderDecorator.php, src/Model/Checkout.php, src/Model/Subscription.php, vendor/pagarme/ecommerce-module-core/src/Payment/Aggregates/Payments/AbstractCreditCardPayment.php, vendor/pagarme/ecommerce-module-core/src/Payment/Factories/PaymentFactory.php, vendor/pagarme/pagarmecoreapi/src/Models/CreateCreditCardPaymentRequest.php
=> Recurrence Flag on Mark1-V5

src/Controller/Gateways/CreditCard.php
feat: hide card list on gateway
=> feat: hide card list on gateway

src/Model/Config.php
This reverts commit f1694d1c1d89bfb583841c4d850d54cb95c2435b, reversing changes made to d4228c3a78656c52687d08745178b36e1b927ca0.
=> Revert "feat: show voucher on gateway type"

assets/javascripts/front/checkout/model/payment/card.js, assets/javascripts/front/checkout/model/payment/order-value.js, catalog-info.yaml, composer.json, constants.php, package.json, readme.txt, src/Block/Adminhtml/Sales/Order/MetaBox/Modal.php, src/Concrete/WoocommercePlatformOrderDecorator.php, src/Controller/HubAccounts.php, src/Controller/Settings.php, src/Model/Charge.php, src/Model/Config.php, src/Model/Subscription.php, src/Service/AccountService.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Log/BlurData.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Services/LogService.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderLogService.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Account.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Account/PaymentEnum.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Account/PaymentMethodSettings.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Account/StoreSettings.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Account/VoucherSettings.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/ModelWithErrors.php, woo-pagarme-payments.php
- Failed to renew order manually with credit card;
- Credit card validation failure when changing delivery method;
- High memory usage when receiving Charge webhook;
- Failed in view installments for 2 credit cards;
- Orders with refunds in the charge display an error in the admin;
=> Release 3.1.7

composer.json, constants.php, package.json, readme.txt, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Account.php, woo-pagarme-payments.php
=> Release 3.1.8

.github/workflows/cd_master.yml, .github/workflows/cd_php8.yml, .github/workflows/cd_stg.yml
> [!IMPORTANT]
Adição de variáveis de ambiente para o cd. 
N/A
=> cd: add env to version inputs

src/Controller/Orders.php, src/Model/Order.php
> [!IMPORTANT]
Alterado a validação do theorder para ver se não está vázio ao invés de validar se é nulo.
- Acessar página de edição de produtos
- Acessar página de edição de pedidos
=> fix: bool theorder value in edit product page

catalog-info.yaml
> [!IMPORTANT]
Atualização do catalog-info.yaml.
N/A
=> chore: Update catalog-info.yaml

src/Block/Adminhtml/Sales/Order/MetaBox/AdditionalInformation.php, src/Concrete/WoocommercePlatformCreditmemoDecorator.php, src/Concrete/WoocommercePlatformOrderDecorator.php, src/Controller/Charges.php, src/Controller/Checkout.php, src/Controller/Orders.php, src/Helper/Utils.php, src/Model/Gateway.php, src/Resource/Base.php, src/Service/LogService.php
> [!IMPORTANT]
Compatibilização com php 8.2.
N/A
=> fix: compatibilization with php 8.2

src/Action/OrderActions.php, src/Model/Order.php, src/Model/Subscription.php
> [!IMPORTANT]
Ocorria um bug na visualização de Subscriptions, pois as charges não existiam.
E caso adicionei uma condicional para caso a função **wc_add_notice** não exista.
* Compras;
* Assinaturas.
=> fix: when there are no charges or the wc_add_notice function

src/Model/Customer.php, src/Model/Subscription.php, vendor/pagarme/ecommerce-module-core/src/Middle/Model/Customer.php
> [!IMPORTANT]
Correção de um bug que acontecia caso não existisse um customerId na tabela do Core. Nesse PR caso ele não exista na tabela, ele varre a todos os pedidos da subscriptions até achar um customerId válido para salvar.
* Renovação de subscription com dados no último pedido;
* Renovação de subscription sem dados no último pedido;
* Renovação de subscription com dados e sem o nó de Customer na response;
* Renovação com um cenário de sucesso anterior.
=> fix: search customerId valid before if customerId does not exist

readme.txt
> [!IMPORTANT]
Adição de bugfix ao changelog.
N/A
=> docs: add missed bugfix to changelog

src/Block/Checkout/Form/Installments.php
> [!IMPORTANT]
Parcelamento de cartão sem id no componente html.
Parcelamento de cartão.
=> fix: pass parent construct parameters

composer.json, constants.php, package.json, readme.txt, vendor/composer/installed.php, woo-pagarme-payments.php
> [!IMPORTANT]
Atualização de versão e docs.
N/A
=> build: update version

composer.json, constants.php, package.json, readme.txt, src/Block/Checkout/Form/Installments.php, vendor/composer/installed.php, woo-pagarme-payments.php
=> Release 3.2.1

src/Concrete/WoocommercePlatformOrderDecorator.php, vendor/pagarme/ecommerce-module-core/src/Payment/Aggregates/Address.php
> [!IMPORTANT]
Alterado a validação do campo número para aceitar o valor 0.
Compra com endereço com número 123 com sucesso.
Compra com endereço com número 0 com sucesso.
=> fix: zero in address number field

vendor/pagarme/ecommerce-module-core/src/Kernel/Services/LogService.php
> [!IMPORTANT]
Remoção do hostname que estava quebrando a nova listagem de logs do admin.
Acessado log no admin e baixado.
=> fix: log name with dot

src/Core.php, tests/Model/CoreTest.php
> [!IMPORTANT]
Realizando a limpeza da URL na montagem do link do webhook.
Integração
=> fix: webhook problem when there is a path in the url

src/Concrete/WoocommercePlatformOrderDecorator.php, src/Model/Checkout.php, src/Model/Order.php, tests/Concrete/WoocommercePlatformOrderDecoratorTest.php, tests/Model/CheckoutTest.php
> [!IMPORTANT]
Adição do nó de authentication na requisição de create order
Compra de 3ds com autenticação de sucesso(status Y) enviando o nó de authentication e o nó de antifraude como false
Compra de 3ds com autenticação de sem sucesso(status N) enviando o nó de authentication e o nó de antifraude como true
=> feat: add authentication node to create order

src/Controller/Gateways/CreditCard.php, src/Model/Config.php
> [!IMPORTANT]
Mudança da mascara da configuração de valor mínimo de 3ds
Alterado o valor da configuração de valor mínimo de 3ds e validado no checkout.
=> feat: change 3ds min amount config mask

src/Model/Checkout.php
> [!IMPORTANT]
Alteração para salvar sempre o status de 3ds impendente do status da charge 
Validado se o status do 3ds estava na visualização de pedido no admin para status da charge de sucesso
Validado se o status do 3ds estava na visualização de pedido no admin para status da charge de falha
=> fix: authentication metadata when failed charge

src/Model/Config.php
> [!IMPORTANT]
Correção da formatação do campo de valor mínimo do 3ds para caso ele seja vazio
Testado o checkout com valor vazio da config de valor mínimo do 3ds
Testado o checkout com valor preenchido da config de valor mínimo do 3ds
=> fix: empty 3ds min amount config

assets/javascripts/front/checkout/model/payment/card/tds.js, src/Model/Config.php, src/Model/Payment/CreditCard.php
> [!IMPORTANT]
Correção dos bugs abaixo:
- 3ds executando para subscriptions
- Config de valor mínimo de 3ds de valores inteiros
- Token retornando false
Cenários citados nas descrição
=> fix: calling 3ds for subscription

composer.json, constants.php, package.json, readme.txt, src/Controller/Gateways/CreditCard.php, vendor/composer/installed.php, woo-pagarme-payments.php
> [!IMPORTANT]
Atualização da versão do plugin.
N/A
=> build: change version

src/Controller/Gateways/CreditCard.php
> [!IMPORTANT]
Adição dos campos do admin do 3ds.
N/A
=> feat: add 3ds admin options

assets/javascripts/front/checkout/model/payment/card.js
> [!IMPORTANT]
Mascará não esperando para ser aplicada quando o document está ready
N/A
=> fix: mask not waiting for document ready

src/Concrete/WoocommercePlatformOrderDecorator.php, src/Controller/Checkout.php, src/Controller/Gateways/AbstractGateway.php, src/Helper/Utils.php, src/Model/Checkout.php, src/Model/Meta.php, src/Model/Subscription.php, tests/Model/CheckoutTest.php
> [!IMPORTANT]
Acessando e atribuindo metadatas corretamente.
Remoção de códigos não utilizados
Compras e assinaturas novas e antigas.
=> fix: access variables correctly

vendor/pagarme/ecommerce-module-core/src/Kernel/Aggregates/Order.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Repositories/OrderRepository.php
> [!IMPORTANT]
Corrigindo a ordem da busca de charges para pegar a ultima e não a primeira.
Compras com falhas e compras com sucesso.
=> fix: charges order problem

src/Concrete/WoocommercePlatformOrderDecorator.php
> [!IMPORTANT]
* Adicionado impostos no total do pedido quando produto não inclui taxa no preço.
* Compras com as configurações de imposto habilitada e desbilitada
=> fix: add tax to order value

src/Concrete/WoocommerceCoreSetup.php, src/Model/Config.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Abstractions/AbstractModuleCoreSetup.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Services/APIService.php
> [!IMPORTANT]
Enviando dados de InterestType no metadata
Compras com e sem juros, compras com multimeios e pix!
=> PAOPN-745: add interest type to metadata

src/Controller/Gateways/AbstractGateway.php, src/Controller/Gateways/Billet.php, src/Controller/Gateways/CreditCard.php
> [!IMPORTANT]
Correção de imports.
Configurações apagadas.
=> fix: interest logic

src/Controller/Gateways/AbstractGateway.php, src/Controller/Gateways/CreditCard.php
> [!IMPORTANT]
Correção de apenas clicar para ativar meio de pagamento e já conseguir transacionar.
Adição do valor 0 para configuração de bandeira também.
Ativar meio de pagamento e já conseguir transacionar.
=> fix: allow payment and pay

src/Concrete/WoocommerceCoreSetup.php
> [!IMPORTANT]
Comparando com dois iguais em vez de 3.
=> fix: condicional type for interest type

assets/javascripts/admin/pagarme_payments.js
> [!IMPORTANT]
* Chamado a função `fillLegacyInstallmentInterests()` ao selecionar o tipo de parcelamento
* Corrigido a função `fillLegacyInstallmentInterests()` para quando o campo de taxa de juros estiver em branco
* Verificado o juros ao selecionar o tipo de parcelamento como legacy, sem alterar outras configurações
* Verificado o juros ao nos campos padrões ao deixar o campo de juros legacy em branco
=> fix: fill interest on installment type change

composer.json, constants.php, package.json, readme.txt, woo-pagarme-payments.php
=> release: 3.3.1

src/Model/CardInstallments.php
> [!IMPORTANT]
* Corrigido exibição de parcelas quando o valor do pedido é menor que o valor mínimo de parcelas. Closes #462
* Parcela exibida e pedido concluído, tanto nas configurações de parcela legacy, quanto para a padrão
=> fix: one installment when value is less than minimum

composer.json, constants.php, languages/woo-pagarme-payments-pt_BR.po, package.json, readme.txt, woo-pagarme-payments.php
=> Release 3.3.2

assets/javascripts/front/checkout/model/payment/card.js, templates/checkout/form/card.phtml, tests/Concrete/WoocommercePlatformOrderDecoratorTest.php
> [!IMPORTANT]
Correção de um bug quando o cliente preenchia os dados de cartão e trocava de meio de pagamento e fazia alguma alteração (seja por cupom ou alteração de endereço) o campo de bandeira estava perdendo o valor.
Troca de meio de pagamento e estado não reinicializa a bandeira do cartão.
=> fix: brand problem

templates/adminhtml/system/config/form/field/hub/integration.phtml
> [!IMPORTANT]
* Removido `/wp-admin` da URL de desintegração do Hub
* Hub desintegrado através do link
=> fix: hub desintegration url

assets/javascripts/front/checkout/model/payment/card.js
> [!IMPORTANT]
Removi a validação de tempo do Token, como os processos são síncronos, não faz sentido realizar uma validação de tempo.
Removi também a tratativa de ```finally``` pois o comportamento já estoura um Error quando o processo passa do numero de tentativas máximas. 
Issue associada: #474
Testes de cartão.
=> fix: Remoção da validação de expiração do Token

src/Model/Subscription.php
> [!IMPORTANT]
* Adicionado condicional para salvar cartão da forma correta para lojas com HPOS habilitado.
* Adicionado nova assinatura e renovado manualmente pelo admin da loja
=> fix: saving recurrence payment when hpos is enabled

assets/javascripts/front/checkout/model/payment/card.js, assets/javascripts/front/checkout/model/payment/googlepay.js
> [!IMPORTANT]
Corrige submit do googlepay
Google pay e cartão de crédito!
=> fix: submit google pay

assets/javascripts/front/checkout/model/payment/card.js
> [!IMPORTANT]
Ao enviar para o backend os dados, remove o Token para não influenciar outros cenários, por exemplo, carteira ou google pay.
Cenário encontrado após checkout assincrono.
Cenários de sucesso e de erro.
=> fix: remove token after send to backend

composer.json, constants.php, package.json, readme.txt, woo-pagarme-payments.php
=> release: 3.4.0

composer.json, constants.php, package.json, readme.txt, src/Concrete/WoocommercePlatformOrderDecorator.php, woo-pagarme-payments.php
=> Release 3.4.1

src/Concrete/WoocommercePlatformOrderDecorator.php, src/Model/Checkout.php, src/Model/Customer.php, src/Model/Subscription.php, src/Model/SubscriptionMeta.php, tests/Model/CheckoutTest.php
> [!IMPORTANT]
Refatoração de quase todo o fluxo de assinatura;
Adição de uma validação no ato da renovação antecipada para atender o fluxo de identificador da bandeira.
Novas assinaturas
Troca de meio de pagamento
Renovação antecipada
Renovação normal
=> PLATS-15 - improve - check card before send order

vendor/pagarme/ecommerce-module-core/src/Kernel/Services/APIService.php
> [!IMPORTANT]
* Adicionado informação no metadata do request para informar se o pedido foi efetuado no checkout blocks, com valor booleano.
=> feat: add checkout blocks to order metadata

src/Model/Subscription.php, src/Model/SubscriptionMeta.php
> [!IMPORTANT]
Corrige compatibilizações com HPOS
Compras normais e assinaturas com cartão.
=> fix: compatibilization with HPOS

composer.json, constants.php, package.json, readme.txt, woo-pagarme-payments.php
=> Release 2.4.2

src/Model/Checkout.php, src/Service/CustomerService.php
> [!IMPORTANT]
Corrige a criação de conta no momento da compra de uma assinatura
Compras deslogadas e compras logadas em cartão de crédito.
=> fix: create customer account in order created

src/Controller/Checkout/CustomerFields.php
> [!IMPORTANT]
Verifica se o CheckoutBlocks existe e está ativo antes de instanciar classes do CheckoutBlocks
Teste no servidor de STG (Que não possui checkout blocks)
=> refactor: improve handling of checkout blocks document field validation

src/Model/Checkout.php
> [!IMPORTANT]
Criando cartão apenas quando é uma transação de assinatura subsequente.
Compras deslogado de assinatura.
=> fix: recurrence create card only in subsequent

src/Helper/Utils.php
> [!IMPORTANT]
Resolve parte da Issue #480 
Compras normais com e sem CheckoutBlocks.
Compras normais com e sem HPOS ativo.
Compras de assinatura.
=> fix: update billing address retrieval to use WC_Order methods

src/Controller/Gateways/AbstractGateway.php, src/Model/Checkout.php, src/Model/Subscription.php
Adiciona link para a transação na página do pedido, no painel de administração.
=> feat: add link to transaction

tests/Model/CheckoutTest.php
> [!IMPORTANT]
Correção de teste unitário.
=> fix: unit test

src/Controller/Hub.php, src/Controller/HubCommand.php, src/Controller/Webhooks.php, src/Core.php, src/Model/Config.php, src/Model/Gateway.php, tests/Model/CoreTest.php
> [!IMPORTANT]
Alterado chamada para URL de Webhook com função nativa do WooCommerce
Integração testada diretamente em site de cliente
=> improve: get hub url from woo function

composer.json, constants.php, package.json, readme.txt, woo-pagarme-payments.php
Atualização de versões e escrita de change-versions
N/A.
=> Release 3.5.0

composer.json, constants.php, package.json, readme.txt, woo-pagarme-payments.php
> [!IMPORTANT]
Release da versão 3.5.1!
N/A.
=> chore: bump version to 3.5.1 and update changelog

src/Controller/Gateways/CreditCard.php, src/Model/Gateway.php, tests/Concrete/WoocommerceCoreSetupTest.php, vendor/pagarme/ecommerce-module-core/src/Kernel/Services/InstallmentService.php, vendor/pagarme/ecommerce-module-core/src/Recurrence/Aggregates/Plan.php, vendor/pagarme/ecommerce-module-core/src/Recurrence/Services/RecurrenceService.php, vendor/pagarme/ecommerce-module-core/tests/Recurrence/Services/RecurrenceServiceTest.php, vendor/pagarme/ecommerce-module-core/tests/mock/Concrete/PlatformCoreSetup.php
> [!IMPORTANT]
Foi alterado limite máximo de parcelas de 12x para **18x** para todos os clientes PSP
Testado compra em 18x com cartão de crédito e multimeios.
<details>
<summary>Configuração de número máximo de parcelas</summary>
</details>
<details>
<summary>Configuração de número de parcelas sem juros</summary>
</details>
<details>
<summary>Parcelas no Cartão de Crédito</summary>
</details>
<details>
<summary>Parcelas em 2 Cartões de Crédito</summary>
</details>
<details>
<summary>Parcelas em Boleto + Cartão de Crédito</summary>
</details>
<details>
<summary>Parcelas no pedido (Minha conta)</summary>
</details>
<details>
<summary>Parcelas no pedido (Admin)</summary>
</details>
<details>
<summary>Parcelas no pedido (Dash …
=> feat: allow up to 18x installments
